### ISSUE TITLE
improve visualizations

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-COVID19#24]
From @Frijol 

> Graphs should be more skimmable, with titles including more detail: "Exceedances of CWA Permits" rather than "Exeedances"

> More synthesized results would be really helpful; some charts go up and some down but you can't look at them side by side and get an overall impression. Synthesized report could be a difference btw this year & the two averages for each regulation?
- Kelsey, could you help me get a sense of what this would look like? I think I know, but I want to confirm. I am also worried that by focusing on one year, we hide the longer term patterns and _context_ from users (but, you're right, they aren't the argument we want to make)
> We count the number of exceedances & violations and it looks like they're down in a number of places– but this is potentially misleading without the context of the missing info. Can we stack "missing, potentially in violation" on top of the "definitely in violation" number for a clearer result?
- An excellent idea. But I don't think we can do this for CAA (I'm not sure we can know how many are missing...or at least not easily. I am _working_ on that). But for CWA, for sure. Perhaps that stacked bar would be more transparent.

See also #7

**Comment by Frijol** [comment]
Re missing info, makes sense (and, ugh.) we should figure out some way to include that context, ideally on the graph (question marks above the bars + a note about them?)

Re overall picture, maybe it would be easier to make than to try to explain!
