### ISSUE TITLE
More efficient database queries

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-COVID19#31]
Some long-running database queries on the same tables are repeated in different cells of the notebook.  Do the query once and save the dataframe for re-use instead.

**Comment by ericnost** [comment]
Yes, in particular: there are repeated calls to `ECHO_EXPORTER` for background info on NPDES and CAA facilities. I recommend one call to EE for NPDES and then reuse that dataframe, and one call to EE for CAA facilities and then reuse that dataframe.
